// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

class RamMonitor {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RamMonitor(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RamMonitor.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  RamInfo get_ram_info() {
    return _get_ram_info();
  }

  late final _get_ram_infoPtr = _lookup<ffi.NativeFunction<RamInfo Function()>>(
    'get_ram_info',
  );
  late final _get_ram_info = _get_ram_infoPtr.asFunction<RamInfo Function()>();

  int sumar(int a, int b) {
    return _sumar(a, b);
  }

  late final _sumarPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('sumar');
  late final _sumar = _sumarPtr.asFunction<int Function(int, int)>();

  int restar(int a, int b) {
    return _restar(a, b);
  }

  late final _restarPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('restar');
  late final _restar = _restarPtr.asFunction<int Function(int, int)>();
}

final class RamInfo extends ffi.Struct {
  @ffi.UnsignedLong()
  external int total;

  @ffi.UnsignedLong()
  external int free;

  @ffi.UnsignedLong()
  external int used;
}
